version: '3'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - event_reminder_bot_db_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  event_reminder_bot_db_data:
